config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "post#index"
  get 'posts' => 'post#index', as: 'posts'
  get 'posts/new' => 'post#new', as: 'new_post'
  get 'posts/:id' => 'post#show', as: 'post'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def index
        @posts = Post.all
    end
    def show
        @post = Post.find(params[:id])
    end
    def new
        @post = Post.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.erb
<h1>Calico Post Titles</h1>

<% @posts.each do |post| %>
<li><%= link_to post.title, post_path(post) %></li>
<% end %>

<%= link_to 'Add a Post', new_post_path %>

app/views/post/new.html.erb
<h3>Add a new Post</h3>

<%= form_with model: @post do |form|  %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br>
  <%= form.label :content%>
  <%= form.text_field :content %>
 <br>

  <%= form.submit 'Add Post'%>
<% end %>

<%= link_to 'Blog Post Home', posts_path %>

app/views/post/show.html.erb
<h2>Blog Post: <%= @post.title %></h2>

<p><%= @post.content %></p>

<%= link_to 'Blog Post Home', posts_path %>